spring:
  profiles:
    active:
      - dev
---
server:
  port: 7203
spring:
  profiles: dev
  application:
    name: baseframe-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7100/eureka/
---
server:
  port: 7204
spring:
  profiles: test
  application:
    name: baseframe-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7200/eureka/