spring:
  profiles:
    active:
      - dev
---
server:
  port: 7205

spring:
  profiles: dev
  application:
    name: baseframe-core-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource          #当前数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver            #mysql驱动包
    url: jdbc:mysql://localhost:3306/db01                 #数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                         #数据库连接池最小维持连接数
      initial-size: 5                                     #初始化连接数
      max-total: 5                                        #最大连接数
      max-wait-millis: 200

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml      #mybatis 配置文件所在路径
  type-aliases-package: com.houlong.baseframe             # 所有的Entity别名类所在的包
  mapper-locations: classpath:mybatis/mapper/**/*.xml     #mapper映射文件

#注册到eureka
eureka:
  client:
    service-url:   
      defaultZone: http://localhost:7200/eureka/
  instance:
    instance-id: baseframe-core-service-dev   #自定义服务器名称
    prefer-ip-address: true

info:
  app.name: houlong-baseframe
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server:
  port: 7205

spring:
  profiles: test
  application:
    name: baseframe-core-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource          #当前数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver            #mysql驱动包
    url: jdbc:mysql://localhost:3306/db02                #数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                         #数据库连接池最小维持连接数
      initial-size: 5                                     #初始化连接数
      max-total: 5                                        #最大连接数
      max-wait-millis: 200

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml      #mybatis 配置文件所在路径
  type-aliases-package: com.houlong.baseframe  # 所有的Entity别名类所在的包
  mapper-locations: classpath:mybatis/mapper/**/*.xml     #mapper映射文件

#注册到eureka
eureka:
  client:
    service-url:  
      defaultZone: http://localhost:7200/eureka/
  instance:
    instance-id: baseframe-core-service-test   #自定义服务器名称
    prefer-ip-address: true

info:
  app.name: houlong-baseframe
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$